name: Continuous Integration

# env
env:
  REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

  # Trigger this manually
  workflow_dispatch:

jobs:
  build-and-test:
    name: "Build & Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        redis-version: [4, 5]
    steps:
      - uses: actions/checkout@v2
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - run: yarn install
      - run: yarn lint
      - run: yarn test
